name: ci
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
        description: 'Environment to deploy to'
      tf-version:
        type: string
        required: true
        description: 'Terraform version to use'
jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf-version }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Set up SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.10.2/sops-v3.10.2.linux.amd64
          mv sops-v3.10.2.linux.amd64 /usr/local/bin/sops
          chmod +x /usr/local/bin/sops
      - name: Configure Age credentials
        run: |
          echo "${{ secrets.AGE_SECRET_KEY }}" | base64 --decode > age.key
          echo "SOPS_AGE_KEY_FILE=age.key" >> "$GITHUB_ENV"
      - name: Decrypt Terraform variables
        run: |
          sops --output-type json --decrypt nextflow/${{ inputs.env }}.tfvars.json.enc > nextflow/env.tfvars.json
      - name: Terraform format
        run: |
          make format
      - name: Terraform lint
        run: |
          make lint
      - name: Terraform init
        run: |
          make init
      - name: Terraform plan
        run: |
          terraform -chdir=nextflow plan -var-file="env.tfvars.json"
