name: CICD pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: "Run tests and static analysis"
    uses: ./.github/workflows/ci.yml
    with:
      tf-version: 1.12.2
  cd-prod:
    name: "Deploy to live"
    needs: ci
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/cd.yml
    with:
      env: main
      tf-version: 1.12.2
